### ISSUE TITLE
Metadata: Type of Content

### ISSUE THREAD

**Issue by mhirschfeld** [DiSSCo/kb#13]
The type of output / content should be added to the meta data fields. During the early project phase we were collecting meta data fields for project outputs (Check with Sabine). I would expect to have information surch as Deliverable, Milestone Report, Data Set, etc.

**Comment by juliapim** [comment]
Ok! I will check with Sabine and add to DiSSCo KB metadata schema. Thank you.

**Comment by SvMering** [comment]
I have sent you an email with detailed information on the metadata fields.
