### ISSUE TITLE
Subject is a concatenation of keywords

### ISSUE THREAD

**Issue by matdillen** [DiSSCo/kb#17]
Currently, the subject filter on the right of a cluster page is a concatenation of all keywords. Could this filter index each keyword individually?

e.g., in the ICEDIG cluster, one of the subjects is: `Data models, management, publishing pipelines & services, biodiversity, repository, FAIR data, ICEDIG, DiSSCo, infrastructure, digitization, Zenodo`

https://know.dissco.eu/handle/123456789/4/simple-search?filterquery=Data+models%2C+management%2C+publishing+pipelines+%26+services%2C+biodiversity%2C+repository%2C+FAIR+data%2C+ICEDIG%2C+DiSSCo%2C+infrastructure%2C+digitization%2C+Zenodo&filtername=subject&filtertype=equals

**Comment by juliapim** [comment]
Hi Mathias,
thank you. The keyword should be indexed individually indeed, it must be an error during submission.
I will check and let you know when this is solved.
