### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by emhaston** [DiSSCo/kb#2]
It would be helpful to create a template for the issues, either using one of the standard GitHub ones or creating a customised one.

Option:

Description
[provide more detailed introduction to the issue itself and why it is relevant]

Process to reproduce issues
[ordered list the process to finding and recreating the issue, example below]

Expected result
[describe what you would expect to have resulted from this process]

Current result
[describe what you you currently experience from this process, and thereby explain the bug]

Possible Fix
[not obligatory, but suggest fixes or reasons for the bug]

Issue screenshot
[if relevant, include a screenshot]

**Comment by juliapim** [comment]
It would be very helpful! Lets leave this open to check with the other participants!
