### ISSUE TITLE
ICEDIG D8.2 missing from KB

### ISSUE THREAD

**Issue by hardistyar** [DiSSCo/kb#21]
The ICEDIG deliverable D8.2 'Cost Book of the digitisation infrastructure of DiSSCo' is missing from the knowledge base.

PDF of the RIO journal article can be found here: https://riojournal.com/article/58915/download/pdf/

**Comment by juliapim** [comment]
Hi ALex,
Thanks for letting us know. It is stored now in the ICEDIG WP8 cluster under this url: https://know.dissco.eu/handle/item/153?mode=full
