### ISSUE TITLE
Registration hidden

### ISSUE THREAD

**Issue by Cubey0** [DiSSCo/kb#3]
Registration is hidden down one level below My Space (& this brings back memories of late 2000 My Space for Music) can it be up one level?

**Comment by juliapim** [comment]
Thanks @Cubey0 ! It is possible to move one level up and also change 'My Space' to some other name, I had forgotten about My Space from the 2000. 
Working on that.

**Comment by juliapim** [comment]
@Cubey0 This process is disabled so that we don't have problems with the future SSO tool. It does not really send any email. I'll make it more clear on the KB. Thanks.
