### ISSUE TITLE
CETAF Stable Identifiers overview

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/kb#42]
### Title of document

CETAF Stable Identifiers

### Url where the document can be found

https://docs.google.com/spreadsheets/d/1vHl2xDghffm6HfQhVeruHV6ZAWAnrc-2LPasq0fOyF4

### Keyword

PIDs

**Comment by juliapim** [comment]
Dear Wouter,
thank you for your report. 
I have placed the file inside DiSSCo Tech - System Documentation. 
Please let me know if this should go to other repository. 

https://know.dissco.eu/handle/item/214

**Comment by juliapim** [comment]
> Dear Wouter, thank you for your report. I have placed the file inside DiSSCo Tech - System Documentation. Please let me know if this should go to other repository.
> 
> https://know.dissco.eu/handle/item/214

@wouteraddink
