### ISSUE TITLE
Opening links in new browser tab

### ISSUE THREAD

**Issue by RBGE-Herbarium** [DiSSCo/kb#43]
**Describe the bug**
At present the test website with the projects (https://dissco-kb.naturkundemuseum.berlin/) has links which open in the same browser tab which makes it a bit more difficult to explore something and get back to where you were.

**Expected behavior**
I would expect these links to open in a new browser tab so that I can keep the main home window open.

**Screenshots**
Screenshot of home screen
![image](https://user-images.githubusercontent.com/63307210/136532922-01034be5-bcc4-4dae-ac83-4556fefd83ad.png)

**Additional context**
It's possible that it is actually preferred by the system and many users to open in the same browser tab, but I wanted to check that the options had been considered.

**Comment by falkogloeckler** [comment]
I think this is a general issue of different preferences of users.
All browsers allow to open links in new tabs (by right clicking and choose "Open in new tab").
If we did this by default there is no option to open in the same tab. So, I'd strongly suggest to have "same tab" as default behavior.
