### ISSUE TITLE
DOI 10.34960/8mzj-g791 doesn't resolve.

### ISSUE THREAD

**Issue by hardistyar** [DiSSCo/kb#44]
The DOI 10.34960/8mzj-g791 is given on this page: https://know.dissco.eu/handle/item/139?mode=full as the identifier of D9.2 DiSSCo Prepare Data Management Plan. It doesn't resolve.

**Comment by SvMering** [comment]
Thank you for pointing this out! The DOI was made findable some time ago and does resolve now.
