### ISSUE TITLE
Diacritics mangled 

### ISSUE THREAD

**Issue by Cubey0** [DiSSCo/kb#45]
**Describe the bug**
Diacritics mangled 

**Expected behavior**
Acented characters 

**Screenshots**

![KB diaritics](https://user-images.githubusercontent.com/9530904/144609158-73e7aa2a-7378-4cc3-a3e6-ed1dbfc03640.jpg)

**Additional context**
Code page issue I thunk

**Comment by juliapim** [comment]
Thank you, Rob!
It was during a batch import that I was testing, and I needed to change a special character. Now it is fixed. 
https://dissco-kb.naturkundemuseum.berlin/simple-search?query=
