### ISSUE TITLE
Registration does not send email

### ISSUE THREAD

**Issue by Cubey0** [DiSSCo/kb#5]
No sign of registration Email (after 10 mins) - longest I would wait before going off and doing something else. (inc, checking  SPAM)

**Comment by Cubey0** [comment]
https://github.com/DiSSCo/kb/issues/3

**Comment by juliapim** [comment]
@Cubey0 This process is disabled so that we don't have problems with the future SSO tool. It does not really send any email. I'll make it more clear on the KB. Thanks.
