### ISSUE TITLE
Feedback - form vs e-mail

### ISSUE THREAD

**Issue by emhaston** [DiSSCo/kb#6]
In the How to Start guidance, there is instructions on how to send feedback.

**Context**

It might be an idea to provide a link to an online form to capture feedback.

**Process**

Add Click Here to send feedback.

**Current result**

Currently need to go into a separate e-mail tool to enter any feedback which may not be easy in some circumstances.

**Possible Fix**

Create an online form to capture feedback. This can then be structured to make capturing the feedback in a more useful way and to make it easier to assess.

**issue screenshot**

Current instructions
![image](https://user-images.githubusercontent.com/6713716/113273981-143a8180-92d5-11eb-8f06-ac4a9ae4ded5.png)

**Comment by juliapim** [comment]
@emhaston Thank you Elspeth. I also agree that an online form will help capturing the feedback in a more useful and easy way. I will make this change.
