### ISSUE TITLE
Browse - elastic formatting of results box

### ISSUE THREAD

**Issue by emhaston** [DiSSCo/kb#7]
**Description**

The elastic formatting of the results box is disconcerting.

**Process to produce issue**

Browse by author
View first 20 results
Click on Next

**Current result**

The width of the results box adjusts significantly when clicking to the next page of results.

**Possible Fix**

The results box could be wider by default to reduce the amount of size changes when moving to the next lot of results.

**issue screenshot**

First page of results
![image](https://user-images.githubusercontent.com/6713716/113275369-a1320a80-92d6-11eb-8d49-7d164116b188.png)

Second page of results
![image](https://user-images.githubusercontent.com/6713716/113276394-b3607880-92d7-11eb-9471-55c254ecc922.png)

**Comment by juliapim** [comment]
@emhaston Thank you for pointing out this error! It was an input error when adding the author's metadata field.
Please check the solved issue.  
<img width="929" alt="kb-author" src="https://user-images.githubusercontent.com/54452216/113289168-2aa20680-92f0-11eb-842e-dfd38b0b84c8.png">
