### ISSUE TITLE
Results box - moving between pages

### ISSUE THREAD

**Issue by emhaston** [DiSSCo/kb#8]
**Description**

Moving between pages of results is not so intuitive. The section at the top to select page number and first letter as well as the option to type the first few letters is really nice! However, the more traditional options that would be expected at the foot of the results page are not present.

**Process to reproduce issues**

Browse by author
Scroll to bottom of results box
Click on next
Scroll to bottom of results box
Click on next

**Expected result**

Would expect additional options:
First
Last
Page Number

**Current result**

Only receiving options of Previous and Next

**Possible Fix**

Add additional options

**Issue screenshot**

![image](https://user-images.githubusercontent.com/6713716/113276735-0afee400-92d8-11eb-938b-8f2fd8f40138.png)

**Comment by juliapim** [comment]
I agree. I will add more options to make the navigation between pages of results is more intuitive. Thanks
